### ISSUE TITLE
Can't run on macOs 13 m1

### ISSUE THREAD

**Issue by foobnix** [jcefmaven/jcefsampleapp#5]
/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/bin/java -javaagent:/Users/dev/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9225.16/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=54057:/Users/dev/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9225.16/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/dev/git/jcefsampleapp/target/classes:/Users/dev/.m2/repository/me/friwi/jcefmaven/110.0.25/jcefmaven-110.0.25.jar:/Users/dev/.m2/repository/me/friwi/jcef-api/jcef-87476e9+cef-110.0.25+g75b1c96+chromium-110.0.5481.78/jcef-api-jcef-87476e9+cef-110.0.25+g75b1c96+chromium-110.0.5481.78.jar:/Users/dev/.m2/repository/me/friwi/jogl-all/v2.4.0-rc-20210111/jogl-all-v2.4.0-rc-20210111.jar:/Users/dev/.m2/repository/me/friwi/gluegen-rt/v2.4.0-rc-20210111/gluegen-rt-v2.4.0-rc-20210111.jar:/Users/dev/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/Users/dev/.m2/repository/com/google/code/gson/gson/2.10/gson-2.10.jar me.friwi.jcefsampleapp.MainFrame
Please consider reporting back whether this build worked on your platform or not.
To report back, follow these 3 (1/2) easy steps (it will take ~1 minute):
    1) Check if everything is working
    2) Go to https://github.com/jcefmaven/jcefmaven/issues/new?assignees=&labels=test+report&template=report_artifact_working.md&title=%5BTR%5D+Test+report
    3) Paste the following report as the issue text. Replace <Y/N> under "Working?" with Y or N.
    4) If the build did not work, make sure to add debug info like console output or screenshots below.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Test report generated by JCefSampleApp
**Tag**
{mvn_version}

**OS (linux/windows/macosx)**
macosx

**Version/Flavor (e.g. Ubuntu 20.04, Windows 10, Big Sur)**
macOS 13.4.1 (13.4.1)

**Arch (amd64/i386/arm64/arm)**
arm64

**Report as working? (Y/N)**
<Y/N>

**Did you test with the official sample app? (Y/N)**
Y

**Additional information**
Your additional info and additional text here, if you want to tell us something.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jul 25, 2023 12:10:42 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: LOCATING |> In progress...
Jul 25, 2023 12:10:42 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: INITIALIZING |> In progress...
Jul 25, 2023 12:10:42 PM me.friwi.jcefmaven.impl.progress.ConsoleProgressHandler handleProgress
INFO: INITIALIZED |> In progress...
initialize on Thread[#27,AWT-EventQueue-0,6,main] with library path /Users/dev/git/jcefsampleapp/jcef-bundle
objc[4649]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x23b85ac60) and /Users/dev/git/jcefsampleapp/jcef-bundle/Chromium Embedded Framework.framework/Libraries/libGLESv2.dylib (0x10748fb58). One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.IllegalAccessError: class org.cef.browser.mac.CefBrowserWindowMac (in unnamed module @0x1d548a08) cannot access class sun.awt.AWTAccessor (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x1d548a08
	at org.cef.browser.mac.CefBrowserWindowMac.getWindowHandle(CefBrowserWindowMac.java:27)
	at org.cef.browser.CefBrowserWr.getWindowHandle(CefBrowserWr.java:337)
	at org.cef.browser.CefBrowserWr.access$600(CefBrowserWr.java:49)
	at org.cef.browser.CefBrowserWr$3.addNotify(CefBrowserWr.java:232)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4846)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4846)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4846)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:721)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/java.awt.Window.addNotify(Window.java:791)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
	at java.desktop/java.awt.Window.pack(Window.java:829)
	at me.friwi.jcefsampleapp.MainFrame.<init>(MainFrame.java:173)
	at me.friwi.jcefsampleapp.MainFrame.main(MainFrame.java:197)

**Comment by FriwiDev** [comment]
Please add the necessary opens as described here: https://github.com/jcefmaven/jcefmaven#limitations
