### ISSUE TITLE
run this example exception

### ISSUE THREAD

**Issue by xcmonline** [jcefmaven/jcefsampleapp#6]
OS: AnolisOS for linux
Tool: Eclipse
JDK: 17.9
Maven: 3.9

Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at org.apache.commons.compress.utils.CountingInputStream.read(CountingInputStream.java:56)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:304)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:738)
	at me.friwi.jcefmaven.impl.step.extract.TarGzExtractor.extractTarGZ(TarGzExtractor.java:47)
	at me.friwi.jcefmaven.CefAppBuilder.install(CefAppBuilder.java:248)
	at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:303)
	at me.friwi.jcefsampleapp.MainFrame.<init>(MainFrame.java:82)
	at me.friwi.jcefsampleapp.MainFrame.main(MainFrame.java:197)

**Comment by FriwiDev** [comment]
My initial guess would be that the download was corrupted. Have you tried it multiple times in a row?
